language: ruby

cache: bundler

matrix:
  include:
    - rvm: 2.3.0
      script:
        - bundle exec danger
    - rvm: 2.3.0
      env: CONCURRENCY=celluloid-io
    - rvm: 2.3.0
      env: CONCURRENCY=faye-websocket
    - rvm: 2.2
    - rvm: 2.1
    - rvm: 2.0
    - rvm: rbx-2
    - rvm: jruby-19mode
    - rvm: ruby-head
    - rvm: jruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: rbx-2

git:
  submodules: false

before_install:
  - gem update bundler
  - gem update --system
