language: ruby

cache: bundler

rvm:
  - 2.5.3
  - 2.6.0
  - ruby-head
  - jruby-head

matrix:
  include:
    - rvm: 2.4.1
      script:
        - bundle exec danger
    - rvm: 2.4.1
      env: CONCURRENCY=celluloid-io
    - rvm: 2.4.1
      env: CONCURRENCY=faye-websocket
    - rvm: 2.5.3
      env: CONCURRENCY=async-websocket
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

git:
  submodules: false

before_install:
  - gem update bundler
  - gem update --system
